name: Build & Push (Secure)

on:
  push:
    branches: [production]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: [ self-hosted, gh ]

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::509399631926:role/github-ecr-push-role
          aws-region: ap-south-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password \
          | docker login --username AWS --password-stdin <account-id>.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build & Push
        run: |
          docker build -t k8s-frontend:${{ github.sha }} .
          docker tag k8s-frontend:${{ github.sha }} \
          <account-id>.dkr.ecr.ap-south-1.amazonaws.com/k8s-frontend:${{ github.sha }}
          docker push <account-id>.dkr.ecr.ap-south-1.amazonaws.com/k8s-frontend:${{ github.sha }}
