name: Build & Push (Secure)

on:
  push:
    branches: [production]

concurrency:
    group: dev  
    cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: [ self-hosted, gh ]

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::509399631926:role/gh-OIDS
          aws-region: us-east-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password \
          | docker login --username AWS --password-stdin 509399631926dkr.ecr.ap-south-1.amazonaws.com

      - name: Build & Push
        run: |
          docker build -t k8s-frontend:${{ github.sha }} .
          docker tag k8s-frontend:${{ github.sha }} \
          509399631926.dkr.ecr.ap-south-1.amazonaws.com/k8s-frontend:${{ github.sha }}
          docker push 509399631926.dkr.ecr.ap-south-1.amazonaws.com/k8s-frontend:${{ github.sha }}
